services:
  app:
    container_name: sistema-freire-app
    image: node:20-alpine
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173" 
    environment:
      # Sobrescribimos "localhost:5437" por el nombre del servicio de la bd ("db") y puerto interno
      DATABASE_URL: "postgresql://freire:Freire123@db:5432/sistema-freire"
    # Instalamos y levantamos el ambiente con soporte para red externa (0.0.0.0)
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - freire_network

  db:
    container_name: sistema-freire
    # IMPORTANTE: Regresamos a la versión 15 porque tu volumen existente fue creado con Postgres 15.
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: freire
      POSTGRES_PASSWORD: Freire123
      POSTGRES_DB: sistema-freire
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U freire -d sistema-freire"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - freire_network

volumes:
  postgres_data:

networks:
  freire_network:
    driver: bridge
